### ISSUE TITLE
Installing package via git on windows fails with Filename Too Long

### ISSUE THREAD

**Issue by eliottness** [DataDog/dd-apm-test-agent#188]
Running the following command on windows:
```
pip install git+https://github.com/DataDog/dd-apm-test-agent.git
```

Result in the following error:
```
error: unable to create file releasenotes/notes/clearing-sessions-now-only-removes-traces,-instead-of-sessions,-requsting-traces-will-now-return-a-404-error-for-TracesNotFound-if-a-session-is-specified-and-traces-are-not-found-6b0311673d8b37aa.yaml: Filename too long
```

The workaround is to wait for a pypi package to be released or to use the following docker image: `ghcr.io/datadog/dd-apm-test-agent/ddapm-test-agent:latest` but this does not apply to Github windows runners as they don't have docker

**Comment by Kyle-Verhoog** [comment]
looks like this can easily be mitigated by not including the release notes into the resulting package!
