### ISSUE TITLE
Snapshot tests with no data generate empty file

### ISSUE THREAD

**Issue by Kyle-Verhoog** [DataDog/dd-apm-test-agent#59]
This results in vague 500s from the test agent because the snapshot is empty and doesn't parse correctly. This was probably introduced https://github.com/DataDog/dd-apm-test-agent/commit/56413eb2a400110ea0e2edfde66f2b945bcff243

**Comment by Kyle-Verhoog** [comment]
Looks like the case I saw was not when no traces were received; it was when an error occurred in the snapshot and so the file was created but nothing stored.

**Comment by brettlangdon** [comment]
is there any way we can back propagate errors from the test agent to the test case?

e.g. if the test agent has an error at any point during the session we return that as an error, even if the trace/snapshot was successful.

**Comment by Kyle-Verhoog** [comment]
Yeah they should be propagated back... I'll have to look into the issue I was having locally.

**Comment by Kyle-Verhoog** [comment]
Haven't seen this one in a long time so going to close this as stale
