### ISSUE TITLE
Publish ARM64 docker images

### ISSUE THREAD

**Issue by andrewlock** [DataDog/dd-apm-test-agent#74]
I'd like to use the mock agent on ARM64 as well as x64. AFACIT, there's no reason this _shouldn't_ be possible (the `python:3.9` base image supports it) it's just a bit of a pain as you need to use `buildx`. [I've done this on Windows before](https://andrewlock.net/creating-multi-arch-docker-images-for-arm64-from-windows/) where it's pretty easy, but it should be possible to do here too I think. 

The only downside is that the [VaultVulp/gp-docker-action](https://github.com/VaultVulp/gp-docker-action) action you're using at the moment doesn't seem to support it. There is [an official image for buildx from Docker here](https://github.com/marketplace/actions/docker-setup-buildx) which should be a good starting point.

I'm happy to do the grunt work to replace it if you're happy with that?

**Comment by Kyle-Verhoog** [comment]
sure! i have no objections at all!
