### ISSUE TITLE
Should `metrics.process_id` be ignored by default?

### ISSUE THREAD

**Issue by andrewlock** [DataDog/dd-apm-test-agent#88]
I've just started running some snapshot tests with services running in Windows, and the snapshots are currently failing because of differences in `metrics.process_id`. 

I can add that to the `SNAPSHOT_IGNORED_ATTRS` list, but should that be ignored by default? I see `metrics.system.pid` is already ignored so I guess a secondary question is: which is the "correct" attribute 😅

**Comment by Kyle-Verhoog** [comment]
:+1: we can add it to the default ignores

**Comment by andrewlock** [comment]
Cool, sounds good, I'll do a PR
